### ISSUE TITLE
Ways to Restrict Access?

### ISSUE THREAD

**Issue by mjosh20** [google/simian#10]
Forgive me if I shouldn't be posing this question here.  I see if I use google apps to authorize the users that can log into the Simian itself and I can even stop people from the domain from seeing the page by setting ALLOW_ALL_DOMAIN_USERS_READ_ACCESS to False. But is it possible to keep my Simian install at appspot.com and use google emails to authorize and still restrict which users can even see the Simian page? I'd really would like to only have to pay for Appengine. What are my options?

**Comment by juofmgoblue** [comment]
It looks like if you set ALLOW_ALL_DOMAIN_USERS_READ_ACCOUNT = False, then
it will have the same effect on appspot.com; that is, it appears then no
users will be able to login unless explicitly added to one of the ACL
groups.

https://github.com/google/simian/blob/e298a94d79e242737a5022259e1b829eb1462db3/src/simian/mac/common/auth.py#L95

Please test and let me know what you find...

**Comment by mjosh20** [comment]
Line 95 in auth.py doesn't have that as an option.  The only place I saw ALLOW_ALL_DOMAIN_USERS_READ_ACCESS is in settings.py.  Is that something I need to completely change line 95? Also, I don't have a google apps account.  So I'm need to be able to authorize though normal gmail emails but still only let certain emails see the Simian page.

**Comment by juofmgoblue** [comment]
The link to auth.py:95 was simply evidence that I believe it will work as
your intend on appspot as well.  Set the value to False in settings.py,
then have someone with another @gmail.com account who is not an app owner
and not a member of ACL Groups give it a try.

**Comment by mjosh20** [comment]
Oh, I've done that w/ multiple emails.  Both mine and friends emails.  They can't see the Admin in the menu but they can still see the page and even open stuff about Munki packages as well.

**Comment by juofmgoblue** [comment]
I'm struggling to figure this out.  Are you positive you've toggled the
various to False, and redeployed to App Engine?

https://github.com/google/simian/blob/e298a94d79e242737a5022259e1b829eb1462db3/src/simian/settings.py#L39

**Comment by mjosh20** [comment]
Wow, I was editing the one in the Build folder.  Thank you so much!
