### ISSUE TITLE
Add a .gitignore to the repo that covers things make creates

### ISSUE THREAD

**Issue by thedavidmeister** [google/simian#15]
When following the setup tutorials `make` spits out a whole bunch of stuff onto the filesystem, including the results of unit tests that are specific to the machine.

Adding a `.gitignore` file to the repo would be a simple way to make sure that files specific to the machine simian is currently being built on are not committed to the repo, but organisations can still use git to manage `settings.cfg` and other config - using the google/simian repo as an upstream to periodically merge changes from.

**Comment by sebnash** [comment]
:+1:
