### ISSUE TITLE
Support uploading packages to Google Cloud Storage

### ISSUE THREAD

**Issue by juofmgoblue** [google/simian#17]
There are sometimes issues with uploading large blobs (>1GB) to App Engine Blobstore.  If Simian supported serving blobs in Google Cloud Storage (aka GCS), then admins would be able to work around Blobstore issues by uploading to GCS directly.

Simian could either ingest from GCS and add to it's Blobstore instance, or just serve directly from GCS:
https://cloud.google.com/appengine/docs/python/blobstore/#Python_Using_the_Blobstore_API_with_Google_Cloud_Storage

**Comment by Lockcuff** [comment]
This would be a great feature, I am running into these same issues. Thanks

**Comment by mholtrlc** [comment]
how are things looking on this? I'm in the process of populating our simian instance and uploading seems really slow despite my 40Mbps upload speed.... 75 minutes to upload 1GB of data

**Comment by juofmgoblue** [comment]
Sorry, no news here.  I doubt we'll be able to work on this anytime soon.

**Comment by maximermilov** [comment]
GCS bucket can be specified with BLOBSTORE_GS_BUCKET env variable in app.yaml
