### ISSUE TITLE
Support Munki2 Categories

### ISSUE THREAD

**Issue by Luzifer** [google/simian#4]
> As a user working in a company using Simian / Munki I want to have my applications, especially in a large software catalog, ordered by categories to have a more useful overview which applications are supported by my companies software management.

![screen shot 2014-10-27 at 13 03 20](https://cloud.githubusercontent.com/assets/20142/4790471/77ba799e-5dd1-11e4-891d-49a647f02559.png)

Currently it is possible to use the commandline option for `makepkginfo` from the MunkiTools to generate the dictionary item for categories in the managed package:

```
makepkginfo --category=Tools Alfred_2.dmg | pbcopy
```

Sadly this is not very useful for simian administrators who are not using the CLI on a daily base as they tend to forget the flag or mistake the category definition. To solve this it would be useful to have a "Category" field in the web interface they can use to specify the category. Additional an auto-completion would be useful for this field to avoid duplicates like "Tool" and "Tools".

**Comment by Luzifer** [comment]
Any news on this?

**Comment by juofmgoblue** [comment]
Apologies for the delay; I've been working on this incrementally over the past 3 days, and I'm getting really close.  It's taking an extra long time since it's been nearly 2 years since we last did a major open source dump, so a lot has changed and thus a lot has broken (https://github.com/google/simian/commit/a24c7cee1b87c0eac46e133648a275273a3326db).

**Comment by juofmgoblue** [comment]
Quick update.  Our open-source scrubbing scripts are all updated and working as expected.  I have Simian source building, passing tests, and passing real-world use.  This has resulted in thousands of line changes, most of which have been reviewed and committed internally; there's one last change list (~500 lines) pending review, then I should be able to sync this to GitHub.  Best case tomorrow, worst case next week.

**Comment by juofmgoblue** [comment]
Just committed Simian a massive update, which includes

**Comment by juofmgoblue** [comment]
Just committed a massive update (178 changed files with 4,778 additions and 6,743 deletions), which includes support for setting Munki Package Categories in the Simian web UI: https://github.com/google/simian/commit/fd50692aedf3651aa3ae494d97eb143126ee49d5

Tests pass, and I did some limited testing in our open-source environment.  Please test (ideally in a non-default App Engine environment) and reopen if there is still more to do here.  Apologies again for the delay.
