### ISSUE TITLE
FAIL: testSet (settings_datastore_test.DatastoreSettingsTest)

### ISSUE THREAD

**Issue by sillywilly42** [google/simian#56]
For a while now this Simian test has been failing for me. I think it's a DST timezone issue.
I get this output:

```
Testing settings_datastore_test
...F
======================================================================
FAIL: testSet (settings_datastore_test.DatastoreSettingsTest)
testSet (settings_datastore_test.DatastoreSettingsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "src/tests/simian/settings_datastore_test.py", line 98, in testSet
    datetime.timedelta(seconds=1), datetime.datetime.now() - stamp)
AssertionError: datetime.timedelta(0, 1) not greater than datetime.timedelta(0, 3600, 3474)
```

The issue is that the timestamp returned by models.Settings.GetItem('long_name') is an hour in the past. I temporarily fixed it by changing [this line](https://github.com/google/simian/blob/master/src/tests/simian/settings_datastore_test.py#L98) to:

`datetime.timedelta(seconds=3601), datetime.datetime.now() - stamp)`

**Comment by maximermilov** [comment]
Does changing datetime.datetime.now() to datetime.datetime.utcnow() helps?

**Comment by sillywilly42** [comment]
@maximermilov: Yes - that works

**Comment by maximermilov** [comment]
Fixed in https://github.com/google/simian/commit/2a3f021f9c17b8cf11c29b8d32324a76be37dac1
