### ISSUE TITLE
Icons...

### ISSUE THREAD

**Issue by arubdesu** [google/simian#60]
Hey, I notice the more recent commits add icons handling, I tried putting an 'icons' directory in the GCS bucket that my ENV points to with BLOBSTORE_GS_BUCKET, but it's still error'ing. I see something about an ICONS_GCS_BUCKET setting in the code, but not sure how to utilize it. Thanks!

**Comment by maximermilov** [comment]
Hi,

> ICONS_GCS_BUCKET setting in the code, but not sure how to utilize it

you can set it in simian/src/simian/settings.py or in datastore "Settings"
table.

>  I tried putting an 'icons' directory in the GCS bucket

There is new "upload icon" button in package admin.

_____
Maxim

**Comment by arubdesu** [comment]
Thanks! Silly of me not to look in the GUI on the config page, as well!
<img width="420" alt="screenshot 2017-01-26 12 15 22" src="https://cloud.githubusercontent.com/assets/388808/22342097/2a014ef8-e3c1-11e6-96a7-4dc8755c6b23.png">
