### ISSUE TITLE
Missing common.cfg 

### ISSUE THREAD

**Issue by maryniewskij** [google/simian#8]
I'm trying to get simianauth --debug to work.  I believe the issue has to due w/ the CA Issuer is looking for it to use / not commas.  According to the guide, I need to change this in etc/simian/common.cfg but I don't have that file.  Was there a change?

**Comment by juofmgoblue** [comment]
Yes.  There used to be common.cfg, client.cfg and server.cfg, but we combined them into settings.cfg: https://github.com/google/simian/blob/master/etc/simian/settings.cfg

Fixed: https://github.com/google/simian/wiki/SimianAndCertificates

**Comment by maryniewskij** [comment]
Wow, that was a quick response! I’m still a little confused.  I see you removed the reference to common.cfg on the wiki, but how do I change Simian to accept the /’s?

**Comment by juofmgoblue** [comment]
For the required_issuer field, instead of:
   /C=AU/ST=Some-State/O=Internet Widgits Pty Ltd
You'd need:
  C=AU,ST=Some-State,O=Internet Widgits Pty Ltd

Simply omit any leading slash, and swap the rest of them for commas.  Does that help?

**Comment by maryniewskij** [comment]
# The full DN of the CA that Simian certificates are signed by.
required_issuer = CN=ca-server.tapestryschool.org

Thats what I had in the settings.cfg file.  Do I change "CN=ca-server.tapestryschool.org" to C=AU,ST=SOME STATE...ETC.....?

**Comment by juofmgoblue** [comment]
Yes, that's right!

**Comment by juofmgoblue** [comment]
Yep, that's right.

**Comment by johnrandolph** [comment]
Are you building a CA from scratch or using an existing CA? 

If you are building from scratch it is sufficient to say CN=ca-server.tapestryschool.org is the DN for the CA and thus is the required_issuer. If you are reusing a CA then you need to take into account whatever the DN actually is. 

You don't need to add all the other fields like city C, state ST, etc unless if you actually need to or want to.

**Comment by maryniewskij** [comment]
I got it working! Thanks for your help.  I pasted the whole cn= text into the settings.cfg.

Now I'm going to figure out how to restrict users to only certain people to see the simian website. I'm currently looking into OAuth 2.0

Thanks again!
